name: Commit check

on:
  push:
    branches:
      - master

env:
  COMMIT_OWNER: ${{ github.event.pusher.name }}
  COMMIT_SHA: ${{ github.sha }}
  PIPELINE_ID: ${{ github.run_number }}
  FORCE_COLOR: 1

jobs:
  commit:
    name: commit
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"

      - name: checkout
        uses: actions/checkout@v4

      - name: check
        run: |
          earthly --ci --allow-privileged +ci-check \
          --PIPELINE_ID=${{ env.PIPELINE_ID }}
      - name: echo
        run: |
          echo $GPG_PRIVATE_KEY_1
          echo $GPG_PASSPHRASE_1
          echo $OSSRH_TOKEN_USERNAME_1
          echo $OSSRH_TOKEN_PASSWORD_1
        env:
          GPG_PRIVATE_KEY_1: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE_1: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_TOKEN_USERNAME_1: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          OSSRH_TOKEN_PASSWORD_1: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
#      - name: publish
#        run: |
#          echo "${{ secrets.GPG_PRIVATE_KEY }}" >> ./gpg_private_key
#          earthly --ci --allow-privileged --push \
#          --secret GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }} \
#          --secret OSSRH_TOKEN_USERNAME=${{ secrets.OSSRH_TOKEN_USERNAME }} \
#          --secret OSSRH_TOKEN_PASSWORD=${{ secrets.OSSRH_TOKEN_PASSWORD }} \
#          +ci-publish \
#          --PIPELINE_ID=${{ env.PIPELINE_ID }}
